version: "3"
services:
    db:
        image: postgres:13
        environment:
            POSTGRES_DB: dfirtrack
            POSTGRES_USER: ${pg_user}
            POSTGRES_PASSWORD: ${pg_password}
        volumes:
          - db-data:/var/lib/postgresql/data
          
    dfirtrack:
        build: 
          context: ../
          dockerfile: ./docker/Dockerfile
          args:
            - pgpass_user=${pg_user}
            - pgpass_pw=${pg_password}
            - django_secret_key=${django_secret_key}
            - openssl_o=${openssl_o}
            - fqdn=${fqdn}
            - openssl_ou=${openssl_ou}
            - disable_https=${disable_https}
        ports:
          - 80:80
          - 443:443
        depends_on:
          - db
         

volumes:
    db-data: